### PR TITLE
Making orders async

### PR DESCRIPTION
**Pull request by olotenko**
End goal is to showcase the use of MP features to declaratively use (asynchronous) REST Client. The actual declarative use of MP REST Client will be done in the future, as it will benefit from request format changes (eg don't use full URL, only the data to pass to the services).

The current Jersey shipped with Helidon 1.4 has issues with RX client, but upgrading to Jersey 2.30+ allows configuring JAX-RS Jersey Connector Provider. In particular, `NettyConnectorProvider`, which I would recommend for use with Helidon, since it is also Netty-based.

Additionally, intrusive testware changes to eliminate the declaration of `clear()` test method.

### CODE REVIEW

**Review by olotenko — COMMENTED** [review]
https://github.com/helidon-sock-shop/orders/pull/1/commits/99fe342e301da552841c15df2b776e91d2c35b5f#diff-58341d9f28c534c467bedf1408975df5R111 - there appears to be an issue with the use of `ExceptionMapper` with asynchronous request handlers - `resume` of the response with exception does not appear to produce the response that `ExceptionMapper` sets up. I can't reproduce this issue with Helidon 2.0, maybe some later Jersey version takes care of it.

Actually, I know what's going on there - the chain of `CompletionStage` produces `CompletionException` with the cause being an `OrderException`. I'll submit a separate commit to deal with it properly.

**Comment by aseovic** [comment]
I wish we discussed this a bit before you started working on it...

I'm not sure using async API *for everything* is the way to go, as it makes the code harder to read, which is not the intent. Sure, we can recommend it for production, and implement *some* services to use it, but I  think doing it across the board is probably not what we want (especially if it means that we need to pull in different version of Jersey than what Helidon 1.4.1 uses -- I plan to upgrade to 1.4.2 as soon as it's out, in order to address few of the bugs I ran into, so let's make sure Helidon 1.4.2 uses the version of Jersey client that you need).

It will also be next to impossible to change `NewOrderRequest` payload not to use full URLs -- each service is running behind k8s service with a name that's passed in as the server name, so the server part is absolutely necessary. We never have all the services running in the same process.

Finally, there are some things I like, such as the fix for multiple server issue, and the idea to move `clear` functionality to test repository implementation, but I wish those were submitted as separate PRs, and I would've done the latter a bit differently.

Instead of introducing various `Clear*` interfaces and their implementations, why not simply introduce `TestOrderRepository` interface in the `core` module (within tests):

```java
public interface TestOrderRepository extends OrderRepository {
    void clear();
}
```
Then we would have `DefaultTestOrderRepository`, `MongoTestOrderRepository`, etc. also in corresponding test modules, which would extend and specialize corresponding repository implementation.

That way we could eliminate `clearRepository(OrderRepository)` from various test class implementations and simply change `OrderRepositoryTest.setup` to:

```java
    @BeforeEach
    void setup() {
        ((TestOrderRepository) orders).clear();
    }
```

This would also give us a simple way to add any additional functionality we need (for assertions, etc.) to `TestOrderRepository`, as it is not tied to `clear` alone.

Anyway, let me know what you think about this proposal, and how much time and desire you have to help. We should also get on Zoom to discuss what exactly we want to do for async support.

**Comment by olotenko** [comment]
Re: `TestOrderRepository`. That's what `ClearOrderRepository` is. :) so we are on the same page here. I can rename it, if necessary. https://github.com/olotenko/orders/blob/master/orders-core/src/test/java/io/helidon/examples/sockshop/orders/ClearOrderRepository.java

Regarding `clearRepository` - I thought of that idea, too, but it seems that because those tests do not obtain the repository using CDI, and for it to be a subclass of `ClearOrderRepository` the tests would need to instantiate the test repositories instead of the actual repository implementations.

I did think of moving the commits around, so the refactoring of `clear` method can be merged independently, but originally that refactoring was not the goal, it was only like an afterthought.

Then, of course, I don't mind even if you reject this pull request, and I go away and refactor things, or keep the things you don't want in my fork for my purposes. One of the purposes is to have a complex Helidon-based system for performance testing. One other related purpose is to use MP features, where they are available.

We can discuss more offline.

**Comment by aseovic** [comment]
I'm gonna close this based on our conversation today, and create separate issues in the `orders` module (and other modules that need to be modified to support async API) and assign them to you.

**Pull request closed without merging**
